### ISSUE TITLE
Unable to compile in VS 2017

### ISSUE THREAD

**Issue by nadarajan** [autofac/Examples#10]
I have the latest VS 2017 community edition. When I tried to compile this solution I am getting the following error: The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.

**Comment by tillig** [comment]
You may need to install a newer .NET Core SDK. You can get that here: https://dotnet.microsoft.com/download

That message isn't a VS message, it's the SDK.

**Comment by alexmg** [comment]
The `global.json` file contains the current .NET Core SDK version.
