### ISSUE TITLE
Why Autofac could not run when using reflection to inject it ON .NET 6

### ISSUE THREAD

**Issue by SenkuuChin** [autofac/Examples#26]
## Describe the Bug

I have used Autofac to inject and inverse by this following way. But it could not effect. It was error when I use the interface in controller as injection, the console and website show me that I do not inject the correspond type for it.
NOTES: This way is correct to inject ON .NET5 and .NET 3.x version, but .NET6.

## Steps to Reproduce

In .NET6, just write a test demo project, just like I use to inject the service. and the issues will reproduce.
```c#
public static void Configure(WebApplicationBuilder builder)
        {
            builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
            builder.Host.ConfigureContainer<ContainerBuilder>(containerBuilder =>
            {
                containerBuilder.RegisterModule(new TestModule());
            }
        }
public class TestModule : Autofac.Module{
     protected override void Load(ContainerBuilder builder)
        {
            Assembly[] assemblies = DependencyContext.Default.RuntimeLibraries
                .Where(a => a.Name.StartsWith("Test"))
                .Select(o => Assembly.Load(new AssemblyName(o.Name))).ToArray();

            builder.RegisterAssemblyTypes(assemblies)
            .Where(t => t.GetCustomAttribute<SingleInstanceAttribute>() != null)
            .AsImplementedInterfaces()
            .SingleInstance()
            .PropertiesAutowired();
        }
}
```

## Expected Behavior

It should correctly inject the service.

## Exception with Stack Trace

```text
Microsoft Visual Studio Debug Console
Autofac.Core. DependencyResolutionException: An exception was thrown while activating TestDemo.Controllers.AdminController.
---〉Autofac.Core. DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder’on type TestDemo.Controllers.AdminController’ can be invoked with the available services and parameters:
Cannot resolve parameter ' TestDemo.ITestService testService’of constructor 'Toid .ctor'(TestDemo.ITestService)’.
at Autofac.Core.Activators.Reflection.ReflectionActivator. etAllBindings(ConstructorBinder[] availableConstruoct
ors，IComponentContext context，IEnumerable` 1 parameters)
at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(TComponentContext context，,IEmumeratle`1 parameters)
at Autofac.Core.Activators.Reflection.Reflectionctivator.<ConfigurePipeline>b_11_0(ResolveRequestContext etort，Action 1 next)
.. at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.(c_DisplayClassl4 0.BuildPipelineb_1(ResolveRequestContext ctxt)
at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context，,Action 1
next)
at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c_DisplayClass14_0.(BuildP'ipeline>b_l(ResolveRegqu
estContext ctxt)
at Autofac.Builder.RegistrationBuilder 3.c_DisplayClass41_0. Propertieskutowired>b_Q)(esolveRequestContertctxt，Action 1 next)
at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.(c_DisplayClass14_0.BuildPipeline)b_1(ResolveReqpestContext ctxt)
.atAutofac.Core.Resolving.Midleware.ActivatorErrorHandlingMiddeware. Execute(ResolveRequestContext context，kotion 1 next)
—-- End of inner exception stack trace ---
at Autofac.Core.Resolving .Middleware.hctivatorErrorHandlingMidleware.Execute(ResolveRequestContext context，Ao
tion`1 next)
at Autofac.Core. Resolving.Pipeline.ResolvePipelineBuilder.<>c_DisplayClass14_0.<BuildPipeline)b_1(ResolveRequ
```

## Dependency Versions

Autofac: 

Autofac, Version=6.0.0.0
Autofac.Extensions.DependencyInjection, Version=7.2.0.0
Autofac.Extras.DynamicProxy, Version=6.0.0

**Comment by tillig** [comment]
Is this a problem you've found with one of the examples in this repo?

Note that since Autofac isn't responsible for `DependencyContext` or any of that reflection-related code, we won't be able to provide you guidance there.

I would recommend:

1. Simplify the repro down to a unit test, if possible. The exception shows the name of some types there that aren't in your code and none of the assemblies being scanned are described, so there's a lot we don't know. One unit test, all code shown, no big zip files or projects. I don't see any use of DynamicProxy in here, so that's more stuff to simplify out.
  - Specify the assemblies to scan exactly, no use of `DependencyContext` to remove that from the equation. Possibly just scan the one assembly that has the unit test and all the types in it.
  - Include the types you assume are registered and are trying to resolve.
  - Have the unit test build the container by scanning the assemblies and resolving the thing in question.
  - Remove any `DynamicProxy` usage from the equation.
2. Either explain how this ties to an example here or file this in the [Autofac core repo](https://github.com/autofac/Autofac). This issues list is for problems folks have found in the examples.

**Comment by SenkuuChin** [comment]
> Is this a problem you've found with one of the examples in this repo?
> 
> Note that since Autofac isn't responsible for `DependencyContext` or any of that reflection-related code, we won't be able to provide you guidance there.
> 
> I would recommend:
> 
> 1. Simplify the repro down to a unit test, if possible. The exception shows the name of some types there that aren't in your code and none of the assemblies being scanned are described, so there's a lot we don't know. One unit test, all code shown, no big zip files or projects. I don't see any use of DynamicProxy in here, so that's more stuff to simplify out.
>    
>    * Specify the assemblies to scan exactly, no use of `DependencyContext` to remove that from the equation. Possibly just scan the one assembly that has the unit test and all the types in it.
>    * Include the types you assume are registered and are trying to resolve.
>    * Have the unit test build the container by scanning the assemblies and resolving the thing in question.
>    * Remove any `DynamicProxy` usage from the equation.
> 2. Either explain how this ties to an example here or file this in the [Autofac core repo](https://github.com/autofac/Autofac). This issues list is for problems folks have found in the examples.

I have try another way but still can not. I attach the demo which I write to you.
[TestService.zip](https://github.com/autofac/Examples/files/7864800/TestService.zip)

**Comment by tillig** [comment]
I will reiterate: **Either explain how this ties to an example here or file this [in the Autofac core repo](https://github.com/autofac/Autofac). This issues list is for problems folks have found in the examples.**

Also, it would help to actually see the code here, not posted as a remote repo or zip file. Thanks. (If there's too much code to post... maybe you haven't simplified it enough?)

**Comment by SenkuuChin** [comment]
> 

OK, I've found where problem is. And fixed it. thanks your answer!
