### ISSUE TITLE
No download option for example projects

### ISSUE THREAD

**Issue by Githrepo** [autofac/Examples#7]
There is no option for downloading this project:
https://github.com/autofac/Examples/tree/master/src/WcfExample

**Comment by tillig** [comment]
Updating the title because the larger question is about how to download code here.

**Comment by tillig** [comment]
You can't download individual projects but you can use the "clone or download" link on the main repo page to download the entire example repo. This is possibly more than you will use, however, the examples in some cases communicate with other examples (e.g., the multitenant MVC example communicates with the multitenant WCF example) to illustrate larger concepts. As such, it doesn't make sense to have individual "releases" or "downloads" for just one project at a time.
